image_size: 600 # canvas size
path_svg: ~  # if you want to load a svg file and train from it
skip_live: False # Whether to skip the LIVE phase
style: "iconography" # "pixelart", "sketch"

# train
num_iter: 100 # num_iter per path group
num_stages: 1 # training stages, you can train x strokes, then freeze them and train another x strokes etc
lr_base:
  point: 1
  fill_color: 0.01
  bg: 0.01
  stroke_width: 0.1
  stroke_color: 0.01
lr_scheduler: True

# primitives
num_paths: 50 # number of strokes
path_schedule: 'repeat' # or 'list'
schedule_each: 16 # or [1, 3, 5, 7]
train_stroke: False # train stroke width and color
trainable_bg: False # set the background to be trainable
width: 3 # stroke width
num_segments: 4
segment_init: 'circle' # 'random'
radius: 20
coord_init: 'sparse' # 'random', 'naive', place the first control point
grid: 30 # divide the canvas into n grids
path_reinit: # reinitializing paths
  use: True
  freq: 50 # every 50 iterations
  stop_step: 800 # for SDS fine-tuning
  opacity_threshold: 0.05 # Re-initialize the path if the opacity is lower than the threshold
  area_threshold: 64 # Re-initialize the path if the area is lower than the threshold

# diffusion
model_id: "sd21b" # sd14, sd15, sd21, sd21b, sdxl
ldm_speed_up: False
enable_xformers: True
gradient_checkpoint: False
num_inference_steps: 50 # DDIM sampling step
guidance_scale: 7.5 # CFG
K: 6 # reject sampling
lora_path: ~
use_kagglehub: True
vae_slicing: True
cpu_offload: True

# SDS
sds:
  im_size: 512 # input size
  guidance_scale: 100 # CFG
  grad_scale: 1.0 # the weight of SDS grads
  t_range: [ 0.05, 0.95 ] # timestep range
  num_iter: 100 # fine-tuning steps

# LIVE loss
use_distance_weighted_loss: True
xing_loss_weight: 0.01
# color penalty loss for pixel-art
penalty_weight: 0.05